/**
 * Here’s My Church directory countries + admin-1 regions.
 * Generated from heresmychurch regions-intl + US states — do not hand-edit region lists.
 * Regenerate: node scripts/generate-hmc-directory.mjs (from HMC checkout).
 *
 * Mirrored from harvous/src/utils/hmc-directory.ts — keep both copies in sync
 * when the source is regenerated (this site has no build-time access to the
 * app repo).
 */

export type HmcRegionOption = { code: string; label: string };

export type HmcCountryConfig = {
  code: string;
  name: string;
  regionNoun: { one: string; many: string };
};

export const HMC_COUNTRIES: ReadonlyArray<HmcCountryConfig> = [
  { code: 'US', name: 'United States', regionNoun: { one: 'state', many: 'states' } },
  { code: 'CA', name: 'Canada', regionNoun: { one: 'province', many: 'provinces and territories' } },
  { code: 'GB', name: 'United Kingdom', regionNoun: { one: 'region', many: 'regions' } },
  { code: 'IE', name: 'Ireland', regionNoun: { one: 'county', many: 'counties' } },
  { code: 'FR', name: 'France', regionNoun: { one: 'department', many: 'departments' } },
  { code: 'DE', name: 'Germany', regionNoun: { one: 'state', many: 'states' } },
  { code: 'NL', name: 'Netherlands', regionNoun: { one: 'province', many: 'provinces' } },
  { code: 'BE', name: 'Belgium', regionNoun: { one: 'province', many: 'provinces' } },
  { code: 'ES', name: 'Spain', regionNoun: { one: 'province', many: 'provinces' } },
  { code: 'IT', name: 'Italy', regionNoun: { one: 'province', many: 'provinces' } },
  { code: 'PT', name: 'Portugal', regionNoun: { one: 'district', many: 'districts' } },
  { code: 'AT', name: 'Austria', regionNoun: { one: 'state', many: 'states' } },
  { code: 'CH', name: 'Switzerland', regionNoun: { one: 'canton', many: 'cantons' } },
  { code: 'SE', name: 'Sweden', regionNoun: { one: 'county', many: 'counties' } },
  { code: 'NO', name: 'Norway', regionNoun: { one: 'county', many: 'counties' } },
  { code: 'DK', name: 'Denmark', regionNoun: { one: 'region', many: 'regions' } },
  { code: 'FI', name: 'Finland', regionNoun: { one: 'region', many: 'regions' } },
  { code: 'PL', name: 'Poland', regionNoun: { one: 'voivodeship', many: 'voivodeships' } },
  { code: 'AU', name: 'Australia', regionNoun: { one: 'state', many: 'states' } },
];

export const HMC_COUNTRY_CODES: ReadonlySet<string> = new Set(HMC_COUNTRIES.map((c) => c.code));

/** Region abbrev → ISO country. US abbrevs win collisions (same as HMC). */
const REGION_TO_COUNTRY: Record<string, string> = {
  "AL": 'US',
  "AK": 'US',
  "AZ": 'US',
  "AR": 'US',
  "CA": 'US',
  "CO": 'US',
  "CT": 'US',
  "DE": 'US',
  "DC": 'US',
  "FL": 'US',
  "GA": 'US',
  "HI": 'US',
  "ID": 'US',
  "IL": 'US',
  "IN": 'US',
  "IA": 'US',
  "KS": 'US',
  "KY": 'US',
  "LA": 'US',
  "ME": 'US',
  "MD": 'US',
  "MA": 'US',
  "MI": 'US',
  "MN": 'US',
  "MS": 'US',
  "MO": 'US',
  "MT": 'US',
  "NE": 'US',
  "NV": 'US',
  "NH": 'US',
  "NJ": 'US',
  "NM": 'US',
  "NY": 'US',
  "NC": 'US',
  "ND": 'US',
  "OH": 'US',
  "OK": 'US',
  "OR": 'US',
  "PA": 'US',
  "RI": 'US',
  "SC": 'US',
  "SD": 'US',
  "TN": 'US',
  "TX": 'US',
  "UT": 'US',
  "VT": 'US',
  "VA": 'US',
  "WA": 'US',
  "WV": 'US',
  "WI": 'US',
  "WY": 'US',
  "AB": "CA",
  "BC": "CA",
  "MB": "CA",
  "NB": "CA",
  "NL": "CA",
  "NS": "CA",
  "NT": "CA",
  "NU": "CA",
  "ON": "CA",
  "PE": "CA",
  "QC": "CA",
  "SK": "CA",
  "YT": "CA",
  "EAST": "GB",
  "EASTMIDLANDS": "GB",
  "GREATERLONDON": "GB",
  "NORTHEAST": "GB",
  "NORTHWEST": "GB",
  "NORTHERNIRELAND": "GB",
  "SCOTLAND": "GB",
  "SOUTHEAST": "GB",
  "SOUTHWEST": "GB",
  "WALES": "GB",
  "WESTMIDLANDS": "GB",
  "YORKSHIREANDTHEHUMBER": "GB",
  "IECE": "IE",
  "IECN": "IE",
  "IECO": "IE",
  "IECW": "IE",
  "IED": "IE",
  "IEDL": "IE",
  "IEG": "IE",
  "IEKE": "IE",
  "IEKK": "IE",
  "IEKY": "IE",
  "IELD": "IE",
  "IELH": "IE",
  "IELK": "IE",
  "IELM": "IE",
  "IELS": "IE",
  "IEMH": "IE",
  "IEMN": "IE",
  "IEMO": "IE",
  "IEOY": "IE",
  "IERN": "IE",
  "IESO": "IE",
  "IETA": "IE",
  "IEWD": "IE",
  "IEWH": "IE",
  "IEWW": "IE",
  "IEWX": "IE",
  "FR01": "FR",
  "FR02": "FR",
  "FR03": "FR",
  "FR04": "FR",
  "FR05": "FR",
  "FR06": "FR",
  "FR07": "FR",
  "FR08": "FR",
  "FR09": "FR",
  "FR10": "FR",
  "FR11": "FR",
  "FR12": "FR",
  "FR13": "FR",
  "FR14": "FR",
  "FR15": "FR",
  "FR16": "FR",
  "FR17": "FR",
  "FR18": "FR",
  "FR19": "FR",
  "FR21": "FR",
  "FR22": "FR",
  "FR23": "FR",
  "FR24": "FR",
  "FR25": "FR",
  "FR26": "FR",
  "FR27": "FR",
  "FR28": "FR",
  "FR29": "FR",
  "FR2A": "FR",
  "FR2B": "FR",
  "FR30": "FR",
  "FR31": "FR",
  "FR32": "FR",
  "FR33": "FR",
  "FR34": "FR",
  "FR35": "FR",
  "FR36": "FR",
  "FR37": "FR",
  "FR38": "FR",
  "FR39": "FR",
  "FR40": "FR",
  "FR41": "FR",
  "FR42": "FR",
  "FR43": "FR",
  "FR44": "FR",
  "FR45": "FR",
  "FR46": "FR",
  "FR47": "FR",
  "FR48": "FR",
  "FR49": "FR",
  "FR50": "FR",
  "FR51": "FR",
  "FR52": "FR",
  "FR53": "FR",
  "FR54": "FR",
  "FR55": "FR",
  "FR56": "FR",
  "FR57": "FR",
  "FR58": "FR",
  "FR59": "FR",
  "FR60": "FR",
  "FR61": "FR",
  "FR62": "FR",
  "FR63": "FR",
  "FR64": "FR",
  "FR65": "FR",
  "FR66": "FR",
  "FR67": "FR",
  "FR68": "FR",
  "FR69": "FR",
  "FR70": "FR",
  "FR71": "FR",
  "FR72": "FR",
  "FR73": "FR",
  "FR74": "FR",
  "FR75": "FR",
  "FR76": "FR",
  "FR77": "FR",
  "FR78": "FR",
  "FR79": "FR",
  "FR80": "FR",
  "FR81": "FR",
  "FR82": "FR",
  "FR83": "FR",
  "FR84": "FR",
  "FR85": "FR",
  "FR86": "FR",
  "FR87": "FR",
  "FR88": "FR",
  "FR89": "FR",
  "FR90": "FR",
  "FR91": "FR",
  "FR92": "FR",
  "FR93": "FR",
  "FR94": "FR",
  "FR95": "FR",
  "DEBB": "DE",
  "DEBE": "DE",
  "DEBW": "DE",
  "DEBY": "DE",
  "DEHB": "DE",
  "DEHE": "DE",
  "DEHH": "DE",
  "DEMV": "DE",
  "DENI": "DE",
  "DENW": "DE",
  "DERP": "DE",
  "DESH": "DE",
  "DESL": "DE",
  "DESN": "DE",
  "DEST": "DE",
  "DETH": "DE",
  "NLDR": "NL",
  "NLFL": "NL",
  "NLFR": "NL",
  "NLGE": "NL",
  "NLGR": "NL",
  "NLLI": "NL",
  "NLNB": "NL",
  "NLNH": "NL",
  "NLOV": "NL",
  "NLUT": "NL",
  "NLZE": "NL",
  "NLZH": "NL",
  "BEBRU": "BE",
  "BEVAN": "BE",
  "BEVBR": "BE",
  "BEVLI": "BE",
  "BEVOV": "BE",
  "BEVWV": "BE",
  "BEWBR": "BE",
  "BEWHT": "BE",
  "BEWLG": "BE",
  "BEWLX": "BE",
  "BEWNA": "BE",
  "ESA": "ES",
  "ESAB": "ES",
  "ESAL": "ES",
  "ESAV": "ES",
  "ESB": "ES",
  "ESBA": "ES",
  "ESBI": "ES",
  "ESBU": "ES",
  "ESC": "ES",
  "ESCA": "ES",
  "ESCC": "ES",
  "ESCE": "ES",
  "ESCO": "ES",
  "ESCR": "ES",
  "ESCS": "ES",
  "ESCU": "ES",
  "ESGC": "ES",
  "ESGI": "ES",
  "ESGR": "ES",
  "ESGU": "ES",
  "ESH": "ES",
  "ESHU": "ES",
  "ESJ": "ES",
  "ESL": "ES",
  "ESLE": "ES",
  "ESLO": "ES",
  "ESLU": "ES",
  "ESM": "ES",
  "ESMA": "ES",
  "ESML": "ES",
  "ESMU": "ES",
  "ESNA": "ES",
  "ESO": "ES",
  "ESOR": "ES",
  "ESP": "ES",
  "ESPM": "ES",
  "ESPO": "ES",
  "ESS": "ES",
  "ESSA": "ES",
  "ESSE": "ES",
  "ESSG": "ES",
  "ESSO": "ES",
  "ESSS": "ES",
  "EST": "ES",
  "ESTE": "ES",
  "ESTF": "ES",
  "ESTO": "ES",
  "ESV": "ES",
  "ESVA": "ES",
  "ESVI": "ES",
  "ESZ": "ES",
  "ESZA": "ES",
  "ITAG": "IT",
  "ITAL": "IT",
  "ITAN": "IT",
  "ITAO": "IT",
  "ITAP": "IT",
  "ITAQ": "IT",
  "ITAR": "IT",
  "ITAT": "IT",
  "ITAV": "IT",
  "ITBA": "IT",
  "ITBG": "IT",
  "ITBI": "IT",
  "ITBL": "IT",
  "ITBN": "IT",
  "ITBO": "IT",
  "ITBR": "IT",
  "ITBS": "IT",
  "ITBT": "IT",
  "ITBZ": "IT",
  "ITCA": "IT",
  "ITCB": "IT",
  "ITCE": "IT",
  "ITCH": "IT",
  "ITCI": "IT",
  "ITCL": "IT",
  "ITCN": "IT",
  "ITCO": "IT",
  "ITCR": "IT",
  "ITCS": "IT",
  "ITCT": "IT",
  "ITCZ": "IT",
  "ITEN": "IT",
  "ITFC": "IT",
  "ITFE": "IT",
  "ITFG": "IT",
  "ITFI": "IT",
  "ITFM": "IT",
  "ITFR": "IT",
  "ITGE": "IT",
  "ITGO": "IT",
  "ITGR": "IT",
  "ITIM": "IT",
  "ITIS": "IT",
  "ITKR": "IT",
  "ITLC": "IT",
  "ITLE": "IT",
  "ITLI": "IT",
  "ITLO": "IT",
  "ITLT": "IT",
  "ITLU": "IT",
  "ITMB": "IT",
  "ITMC": "IT",
  "ITME": "IT",
  "ITMI": "IT",
  "ITMN": "IT",
  "ITMO": "IT",
  "ITMS": "IT",
  "ITMT": "IT",
  "ITNA": "IT",
  "ITNO": "IT",
  "ITNU": "IT",
  "ITOG": "IT",
  "ITOR": "IT",
  "ITOT": "IT",
  "ITPA": "IT",
  "ITPC": "IT",
  "ITPD": "IT",
  "ITPE": "IT",
  "ITPG": "IT",
  "ITPI": "IT",
  "ITPN": "IT",
  "ITPO": "IT",
  "ITPR": "IT",
  "ITPT": "IT",
  "ITPU": "IT",
  "ITPV": "IT",
  "ITPZ": "IT",
  "ITRA": "IT",
  "ITRC": "IT",
  "ITRE": "IT",
  "ITRG": "IT",
  "ITRI": "IT",
  "ITRM": "IT",
  "ITRN": "IT",
  "ITRO": "IT",
  "ITSA": "IT",
  "ITSI": "IT",
  "ITSO": "IT",
  "ITSP": "IT",
  "ITSR": "IT",
  "ITSS": "IT",
  "ITSV": "IT",
  "ITTA": "IT",
  "ITTE": "IT",
  "ITTN": "IT",
  "ITTO": "IT",
  "ITTP": "IT",
  "ITTR": "IT",
  "ITTS": "IT",
  "ITTV": "IT",
  "ITUD": "IT",
  "ITVA": "IT",
  "ITVB": "IT",
  "ITVC": "IT",
  "ITVE": "IT",
  "ITVI": "IT",
  "ITVR": "IT",
  "ITVS": "IT",
  "ITVT": "IT",
  "ITVV": "IT",
  "PT01": "PT",
  "PT02": "PT",
  "PT03": "PT",
  "PT04": "PT",
  "PT05": "PT",
  "PT06": "PT",
  "PT07": "PT",
  "PT08": "PT",
  "PT09": "PT",
  "PT10": "PT",
  "PT11": "PT",
  "PT12": "PT",
  "PT13": "PT",
  "PT14": "PT",
  "PT15": "PT",
  "PT16": "PT",
  "PT17": "PT",
  "PT18": "PT",
  "PT20": "PT",
  "PT30": "PT",
  "AT1": "AT",
  "AT2": "AT",
  "AT3": "AT",
  "AT4": "AT",
  "AT5": "AT",
  "AT6": "AT",
  "AT7": "AT",
  "AT8": "AT",
  "AT9": "AT",
  "CHAG": "CH",
  "CHAI": "CH",
  "CHAR": "CH",
  "CHBE": "CH",
  "CHBL": "CH",
  "CHBS": "CH",
  "CHFR": "CH",
  "CHGE": "CH",
  "CHGL": "CH",
  "CHGR": "CH",
  "CHJU": "CH",
  "CHLU": "CH",
  "CHNE": "CH",
  "CHNW": "CH",
  "CHOW": "CH",
  "CHSG": "CH",
  "CHSH": "CH",
  "CHSO": "CH",
  "CHSZ": "CH",
  "CHTG": "CH",
  "CHTI": "CH",
  "CHUR": "CH",
  "CHVD": "CH",
  "CHVS": "CH",
  "CHZG": "CH",
  "CHZH": "CH",
  "SEAB": "SE",
  "SEAC": "SE",
  "SEBD": "SE",
  "SEC": "SE",
  "SED": "SE",
  "SEE": "SE",
  "SEF": "SE",
  "SEG": "SE",
  "SEH": "SE",
  "SEI": "SE",
  "SEK": "SE",
  "SEM": "SE",
  "SEN": "SE",
  "SEO": "SE",
  "SES": "SE",
  "SET": "SE",
  "SEU": "SE",
  "SEW": "SE",
  "SEX": "SE",
  "SEY": "SE",
  "SEZ": "SE",
  "NO01": "NO",
  "NO02": "NO",
  "NO03": "NO",
  "NO04": "NO",
  "NO05": "NO",
  "NO06": "NO",
  "NO07": "NO",
  "NO08": "NO",
  "NO09": "NO",
  "NO10": "NO",
  "NO11": "NO",
  "NO12": "NO",
  "NO14": "NO",
  "NO15": "NO",
  "NO16": "NO",
  "NO17": "NO",
  "NO18": "NO",
  "NO19": "NO",
  "NO20": "NO",
  "NO21": "NO",
  "DK81": "DK",
  "DK82": "DK",
  "DK83": "DK",
  "DK84": "DK",
  "DK85": "DK",
  "FI02": "FI",
  "FI03": "FI",
  "FI04": "FI",
  "FI05": "FI",
  "FI06": "FI",
  "FI07": "FI",
  "FI08": "FI",
  "FI09": "FI",
  "FI10": "FI",
  "FI11": "FI",
  "FI12": "FI",
  "FI13": "FI",
  "FI14": "FI",
  "FI15": "FI",
  "FI16": "FI",
  "FI17": "FI",
  "FI18": "FI",
  "FI19": "FI",
  "PLDS": "PL",
  "PLKP": "PL",
  "PLLB": "PL",
  "PLLD": "PL",
  "PLLU": "PL",
  "PLMA": "PL",
  "PLMZ": "PL",
  "PLOP": "PL",
  "PLPD": "PL",
  "PLPK": "PL",
  "PLPM": "PL",
  "PLSK": "PL",
  "PLSL": "PL",
  "PLWN": "PL",
  "PLWP": "PL",
  "PLZP": "PL",
  "AUACT": "AU",
  "AUNSW": "AU",
  "AUNT": "AU",
  "AUQLD": "AU",
  "AUSA": "AU",
  "AUTAS": "AU",
  "AUVIC": "AU",
  "AUWA": "AU",
};

export const HMC_REGIONS_BY_COUNTRY: Readonly<Record<string, ReadonlyArray<HmcRegionOption>>> = {
  "US": [
    { code: "AL", label: "Alabama" },
    { code: "AK", label: "Alaska" },
    { code: "AZ", label: "Arizona" },
    { code: "AR", label: "Arkansas" },
    { code: "CA", label: "California" },
    { code: "CO", label: "Colorado" },
    { code: "CT", label: "Connecticut" },
    { code: "DE", label: "Delaware" },
    { code: "DC", label: "District of Columbia" },
    { code: "FL", label: "Florida" },
    { code: "GA", label: "Georgia" },
    { code: "HI", label: "Hawaii" },
    { code: "ID", label: "Idaho" },
    { code: "IL", label: "Illinois" },
    { code: "IN", label: "Indiana" },
    { code: "IA", label: "Iowa" },
    { code: "KS", label: "Kansas" },
    { code: "KY", label: "Kentucky" },
    { code: "LA", label: "Louisiana" },
    { code: "ME", label: "Maine" },
    { code: "MD", label: "Maryland" },
    { code: "MA", label: "Massachusetts" },
    { code: "MI", label: "Michigan" },
    { code: "MN", label: "Minnesota" },
    { code: "MS", label: "Mississippi" },
    { code: "MO", label: "Missouri" },
    { code: "MT", label: "Montana" },
    { code: "NE", label: "Nebraska" },
    { code: "NV", label: "Nevada" },
    { code: "NH", label: "New Hampshire" },
    { code: "NJ", label: "New Jersey" },
    { code: "NM", label: "New Mexico" },
    { code: "NY", label: "New York" },
    { code: "NC", label: "North Carolina" },
    { code: "ND", label: "North Dakota" },
    { code: "OH", label: "Ohio" },
    { code: "OK", label: "Oklahoma" },
    { code: "OR", label: "Oregon" },
    { code: "PA", label: "Pennsylvania" },
    { code: "RI", label: "Rhode Island" },
    { code: "SC", label: "South Carolina" },
    { code: "SD", label: "South Dakota" },
    { code: "TN", label: "Tennessee" },
    { code: "TX", label: "Texas" },
    { code: "UT", label: "Utah" },
    { code: "VT", label: "Vermont" },
    { code: "VA", label: "Virginia" },
    { code: "WA", label: "Washington" },
    { code: "WV", label: "West Virginia" },
    { code: "WI", label: "Wisconsin" },
    { code: "WY", label: "Wyoming" },
  ],
  "CA": [
    { code: "AB", label: "Alberta" },
    { code: "BC", label: "British Columbia" },
    { code: "MB", label: "Manitoba" },
    { code: "NB", label: "New Brunswick" },
    { code: "NL", label: "Newfoundland and Labrador" },
    { code: "NT", label: "Northwest Territories" },
    { code: "NS", label: "Nova Scotia" },
    { code: "NU", label: "Nunavut" },
    { code: "ON", label: "Ontario" },
    { code: "PE", label: "Prince Edward Island" },
    { code: "QC", label: "Québec" },
    { code: "SK", label: "Saskatchewan" },
    { code: "YT", label: "Yukon" },
  ],
  "GB": [
    { code: "EAST", label: "East" },
    { code: "EASTMIDLANDS", label: "East Midlands" },
    { code: "GREATERLONDON", label: "Greater London" },
    { code: "NORTHEAST", label: "North East" },
    { code: "NORTHWEST", label: "North West" },
    { code: "NORTHERNIRELAND", label: "Northern Ireland" },
    { code: "SCOTLAND", label: "Scotland" },
    { code: "SOUTHEAST", label: "South East" },
    { code: "SOUTHWEST", label: "South West" },
    { code: "WALES", label: "Wales" },
    { code: "WESTMIDLANDS", label: "West Midlands" },
    { code: "YORKSHIREANDTHEHUMBER", label: "Yorkshire and the Humber" },
  ],
  "IE": [
    { code: "IECW", label: "Carlow" },
    { code: "IECN", label: "Cavan" },
    { code: "IECE", label: "Clare" },
    { code: "IECO", label: "Cork" },
    { code: "IEDL", label: "Donegal" },
    { code: "IED", label: "Dublin" },
    { code: "IEG", label: "Galway" },
    { code: "IEKY", label: "Kerry" },
    { code: "IEKE", label: "Kildare" },
    { code: "IEKK", label: "Kilkenny" },
    { code: "IELS", label: "Laoighis" },
    { code: "IELM", label: "Leitrim" },
    { code: "IELK", label: "Limerick" },
    { code: "IELD", label: "Longford" },
    { code: "IELH", label: "Louth" },
    { code: "IEMO", label: "Mayo" },
    { code: "IEMH", label: "Meath" },
    { code: "IEMN", label: "Monaghan" },
    { code: "IETA", label: "North Tipperary" },
    { code: "IEOY", label: "Offaly" },
    { code: "IERN", label: "Roscommon" },
    { code: "IESO", label: "Sligo" },
    { code: "IEWD", label: "Waterford" },
    { code: "IEWH", label: "Westmeath" },
    { code: "IEWX", label: "Wexford" },
    { code: "IEWW", label: "Wicklow" },
  ],
  "FR": [
    { code: "FR01", label: "Ain" },
    { code: "FR02", label: "Aisne" },
    { code: "FR03", label: "Allier" },
    { code: "FR04", label: "Alpes-de-Haute-Provence" },
    { code: "FR06", label: "Alpes-Maritimes" },
    { code: "FR07", label: "Ardèche" },
    { code: "FR08", label: "Ardennes" },
    { code: "FR09", label: "Ariège" },
    { code: "FR10", label: "Aube" },
    { code: "FR11", label: "Aude" },
    { code: "FR12", label: "Aveyron" },
    { code: "FR67", label: "Bas-Rhin" },
    { code: "FR13", label: "Bouches-du-Rhône" },
    { code: "FR14", label: "Calvados" },
    { code: "FR15", label: "Cantal" },
    { code: "FR16", label: "Charente" },
    { code: "FR17", label: "Charente-Maritime" },
    { code: "FR18", label: "Cher" },
    { code: "FR19", label: "Corrèze" },
    { code: "FR2A", label: "Corse-du-Sud" },
    { code: "FR21", label: "Côte-d'Or" },
    { code: "FR22", label: "Côtes-d'Armor" },
    { code: "FR23", label: "Creuse" },
    { code: "FR79", label: "Deux-Sèvres" },
    { code: "FR24", label: "Dordogne" },
    { code: "FR25", label: "Doubs" },
    { code: "FR26", label: "Drôme" },
    { code: "FR91", label: "Essonne" },
    { code: "FR27", label: "Eure" },
    { code: "FR28", label: "Eure-et-Loir" },
    { code: "FR29", label: "Finistère" },
    { code: "FR30", label: "Gard" },
    { code: "FR32", label: "Gers" },
    { code: "FR33", label: "Gironde" },
    { code: "FR2B", label: "Haute-Corse" },
    { code: "FR31", label: "Haute-Garonne" },
    { code: "FR43", label: "Haute-Loire" },
    { code: "FR52", label: "Haute-Marne" },
    { code: "FR68", label: "Haute-Rhin" },
    { code: "FR70", label: "Haute-Saône" },
    { code: "FR74", label: "Haute-Savoie" },
    { code: "FR87", label: "Haute-Vienne" },
    { code: "FR05", label: "Hautes-Alpes" },
    { code: "FR65", label: "Hautes-Pyrénées" },
    { code: "FR92", label: "Hauts-de-Seine" },
    { code: "FR34", label: "Hérault" },
    { code: "FR35", label: "Ille-et-Vilaine" },
    { code: "FR36", label: "Indre" },
    { code: "FR37", label: "Indre-et-Loire" },
    { code: "FR38", label: "Isère" },
    { code: "FR39", label: "Jura" },
    { code: "FR40", label: "Landes" },
    { code: "FR41", label: "Loir-et-Cher" },
    { code: "FR42", label: "Loire" },
    { code: "FR44", label: "Loire-Atlantique" },
    { code: "FR45", label: "Loiret" },
    { code: "FR46", label: "Lot" },
    { code: "FR47", label: "Lot-et-Garonne" },
    { code: "FR48", label: "Lozère" },
    { code: "FR49", label: "Maine-et-Loire" },
    { code: "FR50", label: "Manche" },
    { code: "FR51", label: "Marne" },
    { code: "FR53", label: "Mayenne" },
    { code: "FR54", label: "Meurthe-et-Moselle" },
    { code: "FR55", label: "Meuse" },
    { code: "FR56", label: "Morbihan" },
    { code: "FR57", label: "Moselle" },
    { code: "FR58", label: "Nièvre" },
    { code: "FR59", label: "Nord" },
    { code: "FR60", label: "Oise" },
    { code: "FR61", label: "Orne" },
    { code: "FR75", label: "Paris" },
    { code: "FR62", label: "Pas-de-Calais" },
    { code: "FR63", label: "Puy-de-Dôme" },
    { code: "FR64", label: "Pyrénées-Atlantiques" },
    { code: "FR66", label: "Pyrénées-Orientales" },
    { code: "FR69", label: "Rhône" },
    { code: "FR71", label: "Saône-et-Loire" },
    { code: "FR72", label: "Sarthe" },
    { code: "FR73", label: "Savoie" },
    { code: "FR77", label: "Seien-et-Marne" },
    { code: "FR76", label: "Seine-Maritime" },
    { code: "FR93", label: "Seine-Saint-Denis" },
    { code: "FR80", label: "Somme" },
    { code: "FR81", label: "Tarn" },
    { code: "FR82", label: "Tarn-et-Garonne" },
    { code: "FR90", label: "Territoire de Belfort" },
    { code: "FR95", label: "Val-d'Oise" },
    { code: "FR94", label: "Val-de-Marne" },
    { code: "FR83", label: "Var" },
    { code: "FR84", label: "Vaucluse" },
    { code: "FR85", label: "Vendée" },
    { code: "FR86", label: "Vienne" },
    { code: "FR88", label: "Vosges" },
    { code: "FR89", label: "Yonne" },
    { code: "FR78", label: "Yvelines" },
  ],
  "DE": [
    { code: "DEBW", label: "Baden-Württemberg" },
    { code: "DEBY", label: "Bayern" },
    { code: "DEBE", label: "Berlin" },
    { code: "DEBB", label: "Brandenburg" },
    { code: "DEHB", label: "Bremen" },
    { code: "DEHH", label: "Hamburg" },
    { code: "DEHE", label: "Hessen" },
    { code: "DEMV", label: "Mecklenburg-Vorpommern" },
    { code: "DENI", label: "Niedersachsen" },
    { code: "DENW", label: "Nordrhein-Westfalen" },
    { code: "DERP", label: "Rheinland-Pfalz" },
    { code: "DESL", label: "Saarland" },
    { code: "DESN", label: "Sachsen" },
    { code: "DEST", label: "Sachsen-Anhalt" },
    { code: "DESH", label: "Schleswig-Holstein" },
    { code: "DETH", label: "Thüringen" },
  ],
  "NL": [
    { code: "NLDR", label: "Drenthe" },
    { code: "NLFL", label: "Flevoland" },
    { code: "NLFR", label: "Friesland" },
    { code: "NLGE", label: "Gelderland" },
    { code: "NLGR", label: "Groningen" },
    { code: "NLLI", label: "Limburg" },
    { code: "NLNB", label: "Noord-Brabant" },
    { code: "NLNH", label: "Noord-Holland" },
    { code: "NLOV", label: "Overijssel" },
    { code: "NLUT", label: "Utrecht" },
    { code: "NLZE", label: "Zeeland" },
    { code: "NLZH", label: "Zuid-Holland" },
  ],
  "BE": [
    { code: "BEVAN", label: "Antwerp" },
    { code: "BEBRU", label: "Brussels" },
    { code: "BEVOV", label: "East Flanders" },
    { code: "BEVBR", label: "Flemish Brabant" },
    { code: "BEWHT", label: "Hainaut" },
    { code: "BEWLG", label: "Liege" },
    { code: "BEVLI", label: "Limburg" },
    { code: "BEWLX", label: "Luxembourg" },
    { code: "BEWNA", label: "Namur" },
    { code: "BEWBR", label: "Walloon Brabant" },
    { code: "BEVWV", label: "West Flanders" },
  ],
  "ES": [
    { code: "ESVI", label: "Álava" },
    { code: "ESAB", label: "Albacete" },
    { code: "ESA", label: "Alicante" },
    { code: "ESAL", label: "Almería" },
    { code: "ESO", label: "Asturias" },
    { code: "ESAV", label: "Ávila" },
    { code: "ESBA", label: "Badajoz" },
    { code: "ESPM", label: "Baleares" },
    { code: "ESB", label: "Barcelona" },
    { code: "ESBI", label: "Bizkaia" },
    { code: "ESBU", label: "Burgos" },
    { code: "ESCC", label: "Cáceres" },
    { code: "ESCA", label: "Cádiz" },
    { code: "ESS", label: "Cantabria" },
    { code: "ESCS", label: "Castellón" },
    { code: "ESCE", label: "Ceuta" },
    { code: "ESCR", label: "Ciudad Real" },
    { code: "ESCO", label: "Córdoba" },
    { code: "ESCU", label: "Cuenca" },
    { code: "ESGI", label: "Gerona" },
    { code: "ESSS", label: "Gipuzkoa" },
    { code: "ESGR", label: "Granada" },
    { code: "ESGU", label: "Guadalajara" },
    { code: "ESH", label: "Huelva" },
    { code: "ESHU", label: "Huesca" },
    { code: "ESJ", label: "Jaén" },
    { code: "ESC", label: "La Coruña" },
    { code: "ESLO", label: "La Rioja" },
    { code: "ESGC", label: "Las Palmas" },
    { code: "ESLE", label: "León" },
    { code: "ESL", label: "Lérida" },
    { code: "ESLU", label: "Lugo" },
    { code: "ESM", label: "Madrid" },
    { code: "ESMA", label: "Málaga" },
    { code: "ESML", label: "Melilla" },
    { code: "ESMU", label: "Murcia" },
    { code: "ESNA", label: "Navarra" },
    { code: "ESOR", label: "Orense" },
    { code: "ESP", label: "Palencia" },
    { code: "ESPO", label: "Pontevedra" },
    { code: "ESSA", label: "Salamanca" },
    { code: "ESTF", label: "Santa Cruz de Tenerife" },
    { code: "ESSG", label: "Segovia" },
    { code: "ESSE", label: "Sevilla" },
    { code: "ESSO", label: "Soria" },
    { code: "EST", label: "Tarragona" },
    { code: "ESTE", label: "Teruel" },
    { code: "ESTO", label: "Toledo" },
    { code: "ESV", label: "Valencia" },
    { code: "ESVA", label: "Valladolid" },
    { code: "ESZA", label: "Zamora" },
    { code: "ESZ", label: "Zaragoza" },
  ],
  "IT": [
    { code: "ITAG", label: "Agrigento" },
    { code: "ITAL", label: "Alessandria" },
    { code: "ITAN", label: "Ancona" },
    { code: "ITAO", label: "Aoste" },
    { code: "ITAR", label: "Arezzo" },
    { code: "ITAP", label: "Ascoli Piceno" },
    { code: "ITAT", label: "Asti" },
    { code: "ITAV", label: "Avellino" },
    { code: "ITBA", label: "Bari" },
    { code: "ITBT", label: "Barletta-Andria Trani" },
    { code: "ITBL", label: "Belluno" },
    { code: "ITBN", label: "Benevento" },
    { code: "ITBG", label: "Bergamo" },
    { code: "ITBI", label: "Biella" },
    { code: "ITBO", label: "Bologna" },
    { code: "ITBZ", label: "Bozen" },
    { code: "ITBS", label: "Brescia" },
    { code: "ITBR", label: "Brindisi" },
    { code: "ITCA", label: "Cagliari" },
    { code: "ITCL", label: "Caltanissetta" },
    { code: "ITCB", label: "Campobasso" },
    { code: "ITCI", label: "Carbonia-Iglesias" },
    { code: "ITCE", label: "Caserta" },
    { code: "ITCT", label: "Catania" },
    { code: "ITCZ", label: "Catanzaro" },
    { code: "ITCH", label: "Chieti" },
    { code: "ITCO", label: "Como" },
    { code: "ITCS", label: "Cosenza" },
    { code: "ITCR", label: "Cremona" },
    { code: "ITKR", label: "Crotene" },
    { code: "ITCN", label: "Cuneo" },
    { code: "ITEN", label: "Enna" },
    { code: "ITFM", label: "Fermo" },
    { code: "ITFE", label: "Ferrara" },
    { code: "ITFI", label: "Firenze" },
    { code: "ITFG", label: "Foggia" },
    { code: "ITFC", label: "Forlì-Cesena" },
    { code: "ITFR", label: "Frosinone" },
    { code: "ITGE", label: "Genova" },
    { code: "ITGO", label: "Gorizia" },
    { code: "ITGR", label: "Grosseto" },
    { code: "ITIM", label: "Imperia" },
    { code: "ITIS", label: "Isernia" },
    { code: "ITAQ", label: "L'Aquila" },
    { code: "ITSP", label: "La Spezia" },
    { code: "ITLT", label: "Latina" },
    { code: "ITLE", label: "Lecce" },
    { code: "ITLC", label: "Lecco" },
    { code: "ITLI", label: "Livorno" },
    { code: "ITLO", label: "Lodi" },
    { code: "ITLU", label: "Lucca" },
    { code: "ITMC", label: "Macerata" },
    { code: "ITMN", label: "Mantova" },
    { code: "ITMS", label: "Massa-Carrara" },
    { code: "ITMT", label: "Matera" },
    { code: "ITVS", label: "Medio Campidano" },
    { code: "ITME", label: "Messina" },
    { code: "ITMI", label: "Milano" },
    { code: "ITMO", label: "Modena" },
    { code: "ITMB", label: "Monza e Brianza" },
    { code: "ITNA", label: "Napoli" },
    { code: "ITNO", label: "Novara" },
    { code: "ITNU", label: "Nuoro" },
    { code: "ITOG", label: "Ogliastra" },
    { code: "ITOT", label: "Olbia-Tempio" },
    { code: "ITOR", label: "Oristrano" },
    { code: "ITPD", label: "Padova" },
    { code: "ITPA", label: "Palermo" },
    { code: "ITPR", label: "Parma" },
    { code: "ITPV", label: "Pavia" },
    { code: "ITPG", label: "Perugia" },
    { code: "ITPU", label: "Pesaro e Urbino" },
    { code: "ITPE", label: "Pescara" },
    { code: "ITPC", label: "Piacenza" },
    { code: "ITPI", label: "Pisa" },
    { code: "ITPT", label: "Pistoia" },
    { code: "ITPN", label: "Pordenone" },
    { code: "ITPZ", label: "Potenza" },
    { code: "ITPO", label: "Prato" },
    { code: "ITRG", label: "Ragusa" },
    { code: "ITRA", label: "Ravenna" },
    { code: "ITRC", label: "Reggio Calabria" },
    { code: "ITRE", label: "Reggio Emilia" },
    { code: "ITRI", label: "Rieti" },
    { code: "ITRN", label: "Rimini" },
    { code: "ITRM", label: "Roma" },
    { code: "ITRO", label: "Rovigo" },
    { code: "ITSA", label: "Salerno" },
    { code: "ITSS", label: "Sassari" },
    { code: "ITSV", label: "Savona" },
    { code: "ITSI", label: "Siena" },
    { code: "ITSR", label: "Siracusa" },
    { code: "ITSO", label: "Sondrio" },
    { code: "ITTA", label: "Taranto" },
    { code: "ITTE", label: "Teramo" },
    { code: "ITTR", label: "Terni" },
    { code: "ITTP", label: "Trapani" },
    { code: "ITTN", label: "Trento" },
    { code: "ITTV", label: "Treviso" },
    { code: "ITTS", label: "Trieste" },
    { code: "ITTO", label: "Turin" },
    { code: "ITUD", label: "Udine" },
    { code: "ITVA", label: "Varese" },
    { code: "ITVE", label: "Venezia" },
    { code: "ITVB", label: "Verbano-Cusio-Ossola" },
    { code: "ITVC", label: "Vercelli" },
    { code: "ITVR", label: "Verona" },
    { code: "ITVV", label: "Vibo Valentia" },
    { code: "ITVI", label: "Vicenza" },
    { code: "ITVT", label: "Viterbo" },
  ],
  "PT": [
    { code: "PT01", label: "Aveiro" },
    { code: "PT20", label: "Azores" },
    { code: "PT02", label: "Beja" },
    { code: "PT03", label: "Braga" },
    { code: "PT04", label: "Bragança" },
    { code: "PT05", label: "Castelo Branco" },
    { code: "PT06", label: "Coimbra" },
    { code: "PT07", label: "Évora" },
    { code: "PT08", label: "Faro" },
    { code: "PT09", label: "Guarda" },
    { code: "PT10", label: "Leiria" },
    { code: "PT11", label: "Lisboa" },
    { code: "PT30", label: "Madeira" },
    { code: "PT12", label: "Portalegre" },
    { code: "PT13", label: "Porto" },
    { code: "PT14", label: "Santarém" },
    { code: "PT15", label: "Setúbal" },
    { code: "PT16", label: "Viana do Castelo" },
    { code: "PT17", label: "Vila Real" },
    { code: "PT18", label: "Viseu" },
  ],
  "AT": [
    { code: "AT1", label: "Burgenland" },
    { code: "AT2", label: "Kärnten" },
    { code: "AT3", label: "Niederösterreich" },
    { code: "AT4", label: "Oberösterreich" },
    { code: "AT5", label: "Salzburg" },
    { code: "AT6", label: "Steiermark" },
    { code: "AT7", label: "Tirol" },
    { code: "AT8", label: "Vorarlberg" },
    { code: "AT9", label: "Wien" },
  ],
  "CH": [
    { code: "CHAG", label: "Aargau" },
    { code: "CHAR", label: "Appenzell Ausserrhoden" },
    { code: "CHAI", label: "Appenzell Innerrhoden" },
    { code: "CHBL", label: "Basel-Landschaft" },
    { code: "CHBS", label: "Basel-Stadt" },
    { code: "CHBE", label: "Bern" },
    { code: "CHFR", label: "Fribourg" },
    { code: "CHGE", label: "Genève" },
    { code: "CHGL", label: "Glarus" },
    { code: "CHGR", label: "Graubünden" },
    { code: "CHJU", label: "Jura" },
    { code: "CHLU", label: "Lucerne" },
    { code: "CHNE", label: "Neuchâtel" },
    { code: "CHNW", label: "Nidwalden" },
    { code: "CHOW", label: "Obwalden" },
    { code: "CHSG", label: "Sankt Gallen" },
    { code: "CHSH", label: "Schaffhausen" },
    { code: "CHSZ", label: "Schwyz" },
    { code: "CHSO", label: "Solothurn" },
    { code: "CHTG", label: "Thurgau" },
    { code: "CHTI", label: "Ticino" },
    { code: "CHUR", label: "Uri" },
    { code: "CHVS", label: "Valais" },
    { code: "CHVD", label: "Vaud" },
    { code: "CHZG", label: "Zug" },
    { code: "CHZH", label: "Zürich" },
  ],
  "SE": [
    { code: "SEK", label: "Blekinge" },
    { code: "SEW", label: "Dalarna" },
    { code: "SEX", label: "Gävleborg" },
    { code: "SEI", label: "Gotland" },
    { code: "SEN", label: "Halland" },
    { code: "SEZ", label: "Jämtland" },
    { code: "SEF", label: "Jönköping" },
    { code: "SEH", label: "Kalmar" },
    { code: "SEG", label: "Kronoberg" },
    { code: "SEBD", label: "Norrbotten" },
    { code: "SET", label: "Orebro" },
    { code: "SEE", label: "Östergötland" },
    { code: "SEM", label: "Skåne" },
    { code: "SED", label: "Södermanland" },
    { code: "SEAB", label: "Stockholm" },
    { code: "SEC", label: "Uppsala" },
    { code: "SES", label: "Värmland" },
    { code: "SEAC", label: "Västerbotten" },
    { code: "SEY", label: "Västernorrland" },
    { code: "SEU", label: "Västmanland" },
    { code: "SEO", label: "Västra Götaland" },
  ],
  "NO": [
    { code: "NO02", label: "Akershus" },
    { code: "NO09", label: "Aust-Agder" },
    { code: "NO06", label: "Buskerud" },
    { code: "NO20", label: "Finnmark" },
    { code: "NO04", label: "Hedmark" },
    { code: "NO12", label: "Hordaland" },
    { code: "NO15", label: "Møre og Romsdal" },
    { code: "NO17", label: "Nord-Trøndelag" },
    { code: "NO18", label: "Nordland" },
    { code: "NO05", label: "Oppland" },
    { code: "NO03", label: "Oslo" },
    { code: "NO01", label: "Østfold" },
    { code: "NO11", label: "Rogaland" },
    { code: "NO14", label: "Sogn og Fjordane" },
    { code: "NO16", label: "Sør-Trøndelag" },
    { code: "NO21", label: "Svalbard" },
    { code: "NO08", label: "Telemark" },
    { code: "NO19", label: "Troms" },
    { code: "NO10", label: "Vest-Agder" },
    { code: "NO07", label: "Vestfold" },
  ],
  "DK": [
    { code: "DK84", label: "Hovedstaden" },
    { code: "DK82", label: "Midtjylland" },
    { code: "DK81", label: "Nordjylland" },
    { code: "DK85", label: "Sjaælland" },
    { code: "DK83", label: "Syddanmark" },
  ],
  "FI": [
    { code: "FI08", label: "Central Finland" },
    { code: "FI07", label: "Central Ostrobothnia" },
    { code: "FI19", label: "Finland Proper" },
    { code: "FI05", label: "Kainuu" },
    { code: "FI09", label: "Kymenlaakso" },
    { code: "FI10", label: "Lapland" },
    { code: "FI13", label: "North Karelia" },
    { code: "FI14", label: "Northern Ostrobothnia" },
    { code: "FI15", label: "Northern Savonia" },
    { code: "FI12", label: "Ostrobothnia" },
    { code: "FI16", label: "Päijät-Häme" },
    { code: "FI11", label: "Pirkanmaa" },
    { code: "FI17", label: "Satakunta" },
    { code: "FI02", label: "South Karelia" },
    { code: "FI03", label: "Southern Ostrobothnia" },
    { code: "FI04", label: "Southern Savonia" },
    { code: "FI06", label: "Tavastia Proper" },
    { code: "FI18", label: "Uusimaa" },
  ],
  "PL": [
    { code: "PLWP", label: "Greater Poland" },
    { code: "PLKP", label: "Kuyavian-Pomeranian" },
    { code: "PLMA", label: "Lesser Poland" },
    { code: "PLLD", label: "Łódź" },
    { code: "PLDS", label: "Lower Silesian" },
    { code: "PLLU", label: "Lublin" },
    { code: "PLLB", label: "Lubusz" },
    { code: "PLMZ", label: "Masovian" },
    { code: "PLOP", label: "Opole" },
    { code: "PLPD", label: "Podlachian" },
    { code: "PLPM", label: "Pomeranian" },
    { code: "PLSL", label: "Silesian" },
    { code: "PLPK", label: "Subcarpathian" },
    { code: "PLSK", label: "Świętokrzyskie" },
    { code: "PLWN", label: "Warmian-Masurian" },
    { code: "PLZP", label: "West Pomeranian" },
  ],
  "AU": [
    { code: "AUACT", label: "Australian Capital Territory" },
    { code: "AUNSW", label: "New South Wales" },
    { code: "AUNT", label: "Northern Territory" },
    { code: "AUQLD", label: "Queensland" },
    { code: "AUSA", label: "South Australia" },
    { code: "AUTAS", label: "Tasmania" },
    { code: "AUVIC", label: "Victoria" },
    { code: "AUWA", label: "Western Australia" },
  ],
};

export function getHmcCountry(code: string | null | undefined): HmcCountryConfig | undefined {
  const k = (code ?? '').trim().toUpperCase();
  return HMC_COUNTRIES.find((c) => c.code === k);
}

export function getHmcRegionsForCountry(countryCode: string | null | undefined): ReadonlyArray<HmcRegionOption> {
  const k = (countryCode ?? '').trim().toUpperCase();
  return HMC_REGIONS_BY_COUNTRY[k] ?? [];
}

/** Resolve region abbrev → ISO country (US wins collisions). */
export function hmcCountryForRegion(regionAbbrev: string | null | undefined): string | null {
  const k = (regionAbbrev ?? '').trim().toUpperCase();
  return REGION_TO_COUNTRY[k] ?? null;
}

/** Normalize HMC region abbrev if known, else null. */
export function normalizeHmcRegionCode(region: string | null | undefined): string | null {
  const k = (region ?? '').trim().toUpperCase();
  if (!k || !REGION_TO_COUNTRY[k]) return null;
  return k;
}

export function isHmcDirectoryCountry(code: string | null | undefined): boolean {
  return getHmcCountry(code) != null;
}

/** True when value is an HMC ISO code or an exact directory country name. */
export function matchesHmcDirectoryCountry(value: string | null | undefined): boolean {
  const raw = (value ?? '').trim();
  if (!raw) return false;
  if (getHmcCountry(raw)) return true;
  const lower = raw.toLowerCase();
  return HMC_COUNTRIES.some((c) => c.name.toLowerCase() === lower);
}

/**
 * Map Nominatim / free-text place hints to an HMC region abbrev within a country.
 * Prefers ISO3166-2 (`US-TX`, `CA-ON`), then state_code, then region display name.
 */
export function matchHmcRegionInCountry(
  countryCode: string | null | undefined,
  hints: {
    iso3166?: string | null;
    stateCode?: string | null;
    stateName?: string | null;
  },
): string | null {
  const cc = (countryCode ?? '').trim().toUpperCase();
  if (!cc || !HMC_COUNTRY_CODES.has(cc)) return null;
  const regions = getHmcRegionsForCountry(cc);

  const iso = (hints.iso3166 ?? '').trim().toUpperCase();
  if (iso) {
    const parts = iso.split('-');
    if (parts.length >= 2) {
      const isoCc = parts[0]!;
      const isoRegion = parts.slice(1).join('-');
      if (isoCc === cc) {
        const byCode = normalizeHmcRegionCode(isoRegion);
        if (byCode && hmcCountryForRegion(byCode) === cc) return byCode;
        // Some HMC abbrevs are the full ISO tail (AUNSW, GREATERLONDON).
        const direct = regions.find((r) => r.code === isoRegion);
        if (direct) return direct.code;
      }
    }
  }

  const stateCode = (hints.stateCode ?? '').trim().toUpperCase();
  if (stateCode) {
    const byCode = normalizeHmcRegionCode(stateCode);
    if (byCode && hmcCountryForRegion(byCode) === cc) return byCode;
    const inCountry = regions.find((r) => r.code === stateCode);
    if (inCountry) return inCountry.code;
  }

  const stateName = (hints.stateName ?? '').trim().toLowerCase();
  if (stateName) {
    const exact = regions.find((r) => r.label.toLowerCase() === stateName);
    if (exact) return exact.code;
    const starts = regions.find(
      (r) => stateName.startsWith(r.label.toLowerCase()) || r.label.toLowerCase().startsWith(stateName),
    );
    if (starts) return starts.code;
  }

  return null;
}
